version: '3'
services:
  ### DATABASE ###
  feriados-app-postgres:
    image: postgres:latest
    container_name: feriados-app-postgres
    restart: always
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=feriados
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/
      # - /data/hbtn-payments/postgres:/var/lib/postgresql/data
   ### ADMINER ###
  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer
    ports:
      - 8888:8080
    environment:
      - ADMINER_DESIGN=nette
      - ADMINER_DEFAULT_SERVER=feriados-app-postgres

  ### APP ###
  #feriados-app:
    